table BU
	lineageTag: 65eb38b6-a0ad-4974-9a62-9b812a49bfea

	column 'BU Key'
		dataType: double
		isHidden
		lineageTag: e8d3375b-2841-4598-a81a-41d5812ac698
		summarizeBy: none
		sourceColumn: BU Key

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BU
		dataType: string
		lineageTag: 3b06c90b-90e5-4f31-b349-9b79ed55c7cc
		summarizeBy: none
		sourceColumn: BU

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Division
		dataType: string
		lineageTag: c7b8f777-75de-47db-946b-8923d0c09408
		summarizeBy: none
		sourceColumn: Division

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Executive_id
		dataType: int64
		isHidden
		lineageTag: ba6d6c6c-c55b-487a-a6ad-ab81c6185433
		summarizeBy: none
		sourceColumn: Executive_id

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

	hierarchy BUHierarchy
		lineageTag: 49687b17-4ad0-4234-b70f-3b9a93103c81

		level Division
			lineageTag: cad4e3fe-a362-4fe1-bfc5-b0b01e4e5eb0
			column: Division

		level BU
			lineageTag: e57ab715-484d-49be-ba72-d818ba93727b
			column: BU

	partition BU = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT #(lf)       #(lf)      [Profit Center Key] [BU Key],#(lf)   BU,#(lf)   Division, Executive_id#(lf)  FROM [MDS].[mdm].[profitcenter]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"BU Key", "BU Key"}, {"BU", "BU"}, {"Division", "Division"}, {"Executive_id", "Executive_id"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"BU Key", type number}, {"BU", type text}, {"Division", type text}, {"Executive_id", Int64.Type}})
				in
				    #"Changed Type"

