table Customer
	lineageTag: b8bb29fe-9afd-4ca1-9bcc-773a70962eb6

	column Customer
		dataType: double
		isHidden
		lineageTag: 625e6594-dcd7-42e4-b1e7-c46d16b918e8
		summarizeBy: none
		sourceColumn: Customer

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country/Region
		dataType: string
		lineageTag: 995c0713-f35c-41f1-850d-61bd8f78eed6
		summarizeBy: none
		sourceColumn: Country/Region

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Name
		dataType: string
		lineageTag: 7c5bfea6-5a82-4885-8f5c-80f1de0927fc
		summarizeBy: none
		sourceColumn: Name

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column City
		dataType: string
		lineageTag: 4450b194-6b2b-40c2-b4ba-dfc2bafcc319
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Postal Code'
		dataType: double
		lineageTag: d3ee3770-87be-4b1c-893d-944adc35d9fd
		dataCategory: PostalCode
		summarizeBy: count
		sourceColumn: Postal Code

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column State
		dataType: string
		lineageTag: baefbb72-e7d1-4627-8ffa-252c1fc600a4
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Industry ID'
		dataType: double
		isHidden
		lineageTag: bb3f5688-f865-49d1-b293-2870d2666a5e
		summarizeBy: none
		sourceColumn: Industry ID

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy CustomerHierarchy
		lineageTag: 24b4530d-eeb3-4678-9773-5ec05f42be96

		level Country
			lineageTag: d44ecb2b-9f94-4a95-b0ed-4baaefded4ae
			column: Country/Region

		level State
			lineageTag: a770bc64-f08a-4496-aa27-e4bd40252ae6
			column: State

		level City
			lineageTag: 63a559e6-a499-44e9-b4bc-f59a29fa572a
			column: City

		level 'Postal Code'
			lineageTag: 5922b7a2-165d-484d-9bf5-baac9364b2c9
			column: 'Postal Code'

		level Customer
			lineageTag: 385c614b-4f10-4fad-a8dd-6c3e5ee41611
			column: Customer

	partition Customer = m
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mad\Dropbox\Work\Obvience\IP\Customer and Product Profitability\Data\dimCustomer.xlsx"), null, true),
				    Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"Customer", "Customer"}, {"Country", "Country/Region"}, {"Name", "Name"}, {"City", "City"}, {"Postal Code", "Postal Code"}, {"State", "State"}, {"Industry ID", "Industry ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Customer", type number}, {"Country/Region", type text}, {"Name", type text}, {"City", type text}, {"Postal Code", type number}, {"State", type text}, {"Industry ID", type number}})
				 in
				    #"Changed Type"

