table Customer
	lineageTag: 7c0008b0-b1bb-4ca7-a44e-5e547f74371d

	column Customer
		dataType: double
		isHidden
		lineageTag: ce163050-3a1e-4ede-97d5-461a8a5f0ec1
		summarizeBy: none
		sourceColumn: Customer

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country/Region
		dataType: string
		lineageTag: 9a402dad-6e53-4428-833a-403fc71dba7a
		summarizeBy: none
		sourceColumn: Country/Region

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Name
		dataType: string
		lineageTag: f8da2892-4205-4c22-8c78-50a4af857df2
		summarizeBy: none
		sourceColumn: Name

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column City
		dataType: string
		lineageTag: c8646e22-49fb-4573-b950-ee7c7876e77a
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Postal Code'
		dataType: double
		lineageTag: 7072e736-456d-44d8-ba88-50b824ff1719
		dataCategory: PostalCode
		summarizeBy: count
		sourceColumn: Postal Code

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column State
		dataType: string
		lineageTag: f539daa9-2621-417e-a355-4a3e3170d4ed
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Industry ID'
		dataType: double
		isHidden
		lineageTag: 9a27ba18-a95b-4097-bf05-7c8b48cf7a4d
		summarizeBy: none
		sourceColumn: Industry ID

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy CustomerHierarchy
		lineageTag: 3686a98c-24c2-47d4-b843-81dc3a4a36c4

		level Country
			lineageTag: e346b109-c373-4247-bf8a-e8b4032d82d0
			column: Country/Region

		level State
			lineageTag: 4a32cf1a-3b61-484d-b924-520baef74d80
			column: State

		level City
			lineageTag: 3d4b1623-a6b5-4014-a863-4c02b510a9ee
			column: City

		level 'Postal Code'
			lineageTag: cda0e839-2025-4a90-990c-ad7cc418894e
			column: 'Postal Code'

		level Customer
			lineageTag: 5e02224e-df0f-4eac-a665-cff12ee64775
			column: Customer

	partition Customer = m
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mad\Dropbox\Work\Obvience\IP\Customer and Product Profitability\Data\dimCustomer.xlsx"), null, true),
				    Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"Customer", "Customer"}, {"Country", "Country/Region"}, {"Name", "Name"}, {"City", "City"}, {"Postal Code", "Postal Code"}, {"State", "State"}, {"Industry ID", "Industry ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Customer", type number}, {"Country/Region", type text}, {"Name", type text}, {"City", type text}, {"Postal Code", type number}, {"State", type text}, {"Industry ID", type number}})
				 in
				    #"Changed Type"

