table Fact
	isHidden
	lineageTag: c340cb13-6778-443d-9a80-5b2f46c7ae94

	measure 'Total Revenue' = SUM([Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bdf0cfb1-f165-42e3-abd0-ba77041deef8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Material Costs' = SUM([Material Costs])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 81cc5dae-ef35-45c5-9791-077c890310f4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Labor Costs Variable' = SUM([Labor Costs Variable])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ad237ef8-c531-48bd-9b4b-cd7044a81fee

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Taxes' = SUM([Taxes])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e2acc37a-5154-4251-8733-7dd0c1293a8c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Rev for Exp Travel' = SUM([Rev for Exp Travel])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 52c4253b-e1de-4a23-ab84-4977c1f249ea

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Travel Expenses' = SUM([Travel Expenses])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0277ee94-16d3-418a-ac9c-7264fbb26a95

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Cost Third Party' = SUM([Cost Third Party])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f939eaa5-bc2d-4cbd-8adb-6fa23b926590

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Subscription Revenue' = SUM([Subscription Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 06e7ec45-b88e-44c7-b448-abaa61c4afae

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Margin' = [Total Revenue]-[Total COGS]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a4c170a2-cec2-4acc-bd15-28686fc3f931

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure GM% = DIVIDE([Gross Margin],[Total Revenue])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 002f30bc-5841-441f-ae7d-5165b3f1c85b

	measure 'YTD Revenue' = TOTALYTD(SUM([Revenue]),'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cc524b79-890a-4a6c-a5de-ab95f7003268

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total COGS' = [Sum of Material Costs]+[Sum of Labor Costs Variable]+[Sum of Taxes]+[Sum of Rev for Exp Travel]+[Sum of Travel Expenses]+[Sum of Cost Third Party]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 82a7cb6c-5cd0-4b34-a228-b8ccc57ac80e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD COGS' = TOTALYTD([Total COGS],'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3b467d76-0d85-4e56-a7fe-80a02147cd7f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD Gross Margin' = TOTALYTD([Gross Margin],'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fe10e017-6df0-4b81-ac7b-fee1c8c391c3

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue SPLY' = CALCULATE([Total Revenue],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cd370f77-7e24-477a-b7d5-607d24c1bbe7

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Margin SPLY' = CALCULATE([Gross Margin],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 07e0853f-0639-4c32-9a31-dba6931fee6f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'GM% SPLY' = [Gross Margin SPLY]/[Revenue SPLY]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d3ca09cf-fca9-4d88-8227-c00e4ad62be5

	measure 'YTD GM%' = [YTD Gross Margin]/[YTD Revenue]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d985cd5f-e2fa-44c5-b26b-b212777f65e1

	measure 'YTD Revenue SPLY' = CALCULATE([YTD Revenue],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 809da5b5-4573-4da6-bdfe-6db5ceb47081

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'COGS SPLY' = CALCULATE([Total COGS],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3dd871db-48ce-4633-adff-db830594c32e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD COGS SPLY' = CALCULATE([YTD COGS],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e9422de9-6ab4-436a-b57b-87ef1b7bf094

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD GM% SPLY' = [YTD GM SPLY]/[YTD Revenue SPLY]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5deb0374-cf9a-499a-a04f-0e0a5a40933b

	measure 'YTD GM SPLY' = CALCULATE([YTD Gross Margin],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 32d5234f-d495-474e-a85f-474247f72ffd

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY Rev Var' = [Total Revenue]-[Revenue SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5fea7f71-f6af-417c-a5cd-0c7ddfe45fa8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY GM Var' = [Gross Margin]-[Gross Margin SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 26362743-8035-4bd9-9942-361b9bb95c3e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY Rev Growth' = IF([Revenue SPLY],[YoY Rev Var]/[Revenue SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 909ac307-ed1a-463c-acaa-05534a9275f2

	measure 'YoY GM Growth' = IF([Gross Margin SPLY],[YoY GM Var]/[Gross Margin SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: cb346c98-7ed2-46aa-b43f-b56471449cc2

	measure 'YoY YTD Rev Var' = [YTD Revenue]-[YTD Revenue SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 05087a22-1aa5-4fee-a23f-70c709d4e226

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY COGS Var' = [Total COGS]-[COGS SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8d47c10b-05cc-4553-b758-21299869bf37

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY YTD COGS Var' = [YTD COGS]-[YTD COGS SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d3e3c7ea-fb61-4c87-84ff-cde3c2d0376b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY YTD GM% Var' = [YTD GM%]-[YTD GM% SPLY]
		formatString: #,0
		lineageTag: 82df98f4-0f3b-4fd9-86ef-2aa26adfbbd4

	measure 'YoY YTD GM Var' = [YTD Gross Margin]-[YTD GM SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6b8a9924-4ade-4051-a6ab-56c5d2a66817

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY GM %Var' = [GM%]-[GM% SPLY]
		lineageTag: fb241ff5-e4ee-492e-808b-d73feb13cb6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY YTD Rev Growth' = IF([YTD Revenue SPLY],[YoY YTD Rev Var]/[YTD Revenue SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: cfefd758-671e-4b6f-bc07-dcfb21bdeec5

	measure 'YoY COGS Growth' = IF([COGS SPLY],[YoY COGS Var]/[COGS SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: afab0e29-118b-4940-8c2b-33a08ca6deb7

	measure 'YoY YTD COGS Growth' = IF([YTD COGS SPLY],[YoY YTD COGS Var]/[YTD COGS SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2077f3dc-3397-47c5-9ceb-3f3728d082ee

	measure 'YoY YTD GM Growth' = IF([YTD GM SPLY],[YoY YTD GM Var]/[YTD GM SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1e50646b-79fd-446c-851e-d0930362572a

	measure '# of Customers' = DISTINCTCOUNT([Customer Key])
		lineageTag: fa128e7b-d614-4075-987e-f7cfb8a115ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# of Products' = DISTINCTCOUNT([Product Key])
		lineageTag: 2cba77a1-29f3-4216-8a28-1259caaf4cb8

		annotation PBI_FormatHint = {"isText":true}

	measure 'Revenue Budget' = CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]="Budget"))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a182bc15-ff3d-4164-97c0-7d049809f9fb

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Var to Budget' = [RevenueTY]-[Revenue Budget]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6ed69c1a-0c11-441c-91bc-7f8f2612bb3f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Var % to Budget' = DIVIDE([Revenue Var to Budget], [RevenueTY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3afeb602-251c-449f-87f1-918cc98ec0f2

	measure RevenueTY = CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]="Actual"))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bffbbc8b-3264-43aa-b321-fde9d0679116

		kpi
			targetExpression = 'Fact'[Revenue Budget]
			targetFormatString: \$#,0;(\$#,0);\$#,0
			statusGraphic: Traffic Light - Single
			statusExpression = ```
				var x='Fact'[RevenueTY]/'Fact'[_RevenueTY Goal] return
				if(ISBLANK(x),BLANK(),
				        If(x<0.95,-1,
					    If(x<1,0,1)
				    )
				)
				
				```

			annotation GoalType = Measure

			annotation KpiStatusType = Linear

			annotation KpiThresholdType = Percentage

			annotation KpiThresholdOrdering = Ascending

			annotation KpiThresholdCount = 2

			annotation KpiThreshold_0 = 95

			annotation KpiThreshold_1 = 100

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Revenue' = SUM('Fact'[Revenue])
		lineageTag: 3a480551-1c4e-483d-ae4a-191f9c9a63f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer Key'
		dataType: int64
		isHidden
		lineageTag: b6fa7975-f649-48e5-8f8c-2f7f8788db0f
		summarizeBy: none
		sourceColumn: Customer Key

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Key'
		dataType: string
		isHidden
		lineageTag: be546161-c1ad-4fe8-87c7-eade132120d5
		summarizeBy: none
		sourceColumn: Product Key

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'BU Key'
		dataType: double
		isHidden
		lineageTag: 2a312ce4-c1f8-42ec-8a1d-d957100890d4
		summarizeBy: none
		sourceColumn: BU Key

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Scenario Key'
		dataType: int64
		isHidden
		lineageTag: 43935323-bbb6-4321-abf5-147842c4660b
		summarizeBy: none
		sourceColumn: Scenario Key

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Revenue
		dataType: double
		isHidden
		lineageTag: e777ef46-526b-43dc-b5a8-860b5501d9ca
		summarizeBy: sum
		sourceColumn: Revenue

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Material Costs'
		dataType: double
		isHidden
		lineageTag: 4f084833-a696-4734-986e-a7a6d7e512d0
		summarizeBy: sum
		sourceColumn: Material Costs

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Labor Costs Variable'
		dataType: double
		isHidden
		lineageTag: 6f172773-d167-4b32-b0ef-ff0644f5f490
		summarizeBy: sum
		sourceColumn: Labor Costs Variable

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Taxes
		dataType: double
		isHidden
		lineageTag: fe89b299-b0b4-4acb-af45-4a097e9266b9
		summarizeBy: sum
		sourceColumn: Taxes

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rev for Exp Travel'
		dataType: double
		isHidden
		lineageTag: 0c859aa5-774a-444f-b658-47f5a6fe8724
		summarizeBy: sum
		sourceColumn: Rev for Exp Travel

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Travel Expenses'
		dataType: double
		isHidden
		lineageTag: 9bab4914-8a0f-4083-9869-50bd71a04620
		summarizeBy: sum
		sourceColumn: Travel Expenses

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Third Party'
		dataType: double
		isHidden
		lineageTag: 99cfb5e8-57fa-4928-af42-0149fb96c1ac
		summarizeBy: sum
		sourceColumn: Cost Third Party

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Subscription Revenue'
		dataType: double
		isHidden
		lineageTag: fec76c56-fd52-4950-be22-7e6fcc522da2
		summarizeBy: sum
		sourceColumn: Subscription Revenue

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearPeriod
		dataType: string
		isHidden
		lineageTag: 1dbb9bf5-0ecb-4412-852a-2f8a0259d2db
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

	partition Fact = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 YearPeriod#(lf)      ,[KNDNR] [Customer Key]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,1 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.20 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f, mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 210 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'#(lf)union all #(lf)SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 PeriodYear#(lf)      ,[KNDNR] [Customer]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,2 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.4 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f tablesample (85 percent),  mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 300 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Customer Key", "Customer Key"}, {"Product Key", "Product Key"}, {"BU Key", "BU Key"}, {"Scenario Key", "Scenario Key"}, {"Revenue", "Revenue"}, {"Material Costs", "Material Costs"}, {"Labor Costs Variable", "Labor Costs Variable"}, {"Taxes", "Taxes"}, {"Rev for Exp Travel", "Rev for Exp Travel"}, {"Travel Expenses", "Travel Expenses"}, {"Cost Third Party", "Cost Third Party"}, {"Subscription Revenue", "Subscription Revenue"}, {"YearPeriod", "YearPeriod"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Customer Key", Int64.Type}, {"Product Key", type text}, {"BU Key", type number}, {"Scenario Key", Int64.Type}, {"Revenue", type number}, {"Material Costs", type number}, {"Labor Costs Variable", type number}, {"Taxes", type number}, {"Rev for Exp Travel", type number}, {"Travel Expenses", type number}, {"Cost Third Party", type number}, {"Subscription Revenue", type number}, {"YearPeriod", type text}})
				in
				    #"Changed Type"

