table Scenario
	lineageTag: 66ca42b3-75a6-4909-95fc-d802e3beb440

	column 'Scenario Key'
		dataType: int64
		isHidden
		lineageTag: dc9268f8-d0b9-42dc-8a42-29b003927182
		summarizeBy: none
		sourceColumn: Scenario Key

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Scenario
		dataType: string
		lineageTag: f81c4c10-87e2-4029-9e03-14662459a098
		summarizeBy: none
		sourceColumn: Scenario

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Scenario = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXJMLilNzFGK1YlWMgJynUpT0lNLlGJjAQ==", BinaryEncoding.Base64), Compression.Deflate))),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Column1", "Scenario Key"}, {"Column2", "Scenario"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Scenario Key", Int64.Type}, {"Scenario", type text}})
				 in
				    #"Changed Type"

