table State
	lineageTag: 341c6ce8-e70c-4107-875d-a007f371cec5

	column StateCode
		dataType: string
		lineageTag: 36c952d2-22f3-4c4d-93f5-434fc39d322b
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: StateCode

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column State
		dataType: string
		lineageTag: facd6e1f-5d9c-47bf-98ad-cb74ccdfc432
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Region
		dataType: string
		lineageTag: 0e7d49b8-670c-4829-8568-dc8ef458c90c
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Region

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition State = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="select StateShort StateCode, StateName State, Region from MDS.mdm.state"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"StateCode", "StateCode"}, {"State", "State"}, {"Region", "Region"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"StateCode", type text}, {"State", type text}, {"Region", type text}})
				in
				    #"Changed Type"

